config/routes.rb
Rails.application.routes.draw do
  resources :games

  root "games#index"

end

app/models/game.rb
class Game < ActiveRecord::Base
  serialize :board, Array

  WINNING_MOVES = [
    [0, 1, 2], [3, 4, 5], [6, 7, 8],
    [0, 3, 6], [1, 4, 7], [2, 5, 8],
    [0, 4, 8], [2, 4, 6]
  ]

  def first_player_active?
    current_player == player_1
  end

  def current_symbol
    first_player_active? ? "O" : "X"
  end

  def inactive_symbol
    first_player_active? ? "X" : "O"
  end

  def switch_user
    self.current_player = first_player_active? ? player_2 : player_1
  end

  def won?
    WINNING_MOVES.any? { |line| win_check?(line) }
  end

  def finished?
    board.all? { |field| field == "X" || field == "O" }
  end

  def win_check?(line)
    line.all? { |value| board[value] == inactive_symbol }
  end

  validates_presence_of :player_1, :player_2

  validate :player_names_are_different

  def player_names_are_different
    if player_1 == player_2
      errors.add(:player_2, "can't be the same as player 1")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    @game.board[params[:index].to_i] = @game.current_symbol
    @game.switch_user
    @game.save!

    redirect_to game_path(@game)
  end

  def new
    @game = Game.new()
  end

  def create
    @game = Game.new(game_params)
    @game.board = (1..9).to_a
    @game.current_player = @game.player_1

    if @game.save
      redirect_to games_path
    else
      render :new
    end
  end

  private

  def game_params
    params[:game].permit(:player_1, :player_2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<h1>Games</h1>

<p>
  <%= link_to "New game", new_game_path %>
</p>

<ol>
  <% @games.each do |game| %>
    <li><%= link_to "#{game.player_1} vs #{game.player_2}", game_path(game) %></li>
  <% end %>
</ol>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= form_for @game do |f| %>
  <% @game.errors.each do |field, message| %>
    <p><%= field %> <%= message %></p>
  <% end %>

  <p>
    <%= f.label :player_1 %><br/>
    <%= f.text_field :player_1 %>
  </p>

  <p>
    <%= f.label :player_2 %><br/>
    <%= f.text_field :player_2 %>
  </p>

  <p>
    <%= f.submit "Create Game" %>
  </p>
<% end %>

app/views/games/show.html.erb
<h1>Game <%= @game.id %></h1>

<% if @game.won? %>
  <h2>Game Over - Player <%= @game.current_player %> Won!</h2>
<% elsif @game.finished? %>
  <h2>Draw</h2>
<% end %>

<h3>Player O: <%= @game.player_1 %></h3>
<h3>Player X: <%= @game.player_2 %></h3>
<h3>Current Player: <%= @game.current_player %></h3>

<% @game.board.each_with_index do |field, index| %>
  <% if index % 3 == 0 %>
    <br/>
  <% end %>

  <% if field == "O" || field == "X" %>
    <%= button_tag field, :disabled => true %>
  <% else %>
    <%= form_for @game do |f| %>
      <%= hidden_field_tag "index", index %>
      <%= f.submit field %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tictactoe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>